### PR TITLE
Add guidance for listing reviewers in DESCRIPTION file

### PR DESCRIPTION
**Pull request by noamross**

### CODE REVIEW

**Comment by lmullen** [comment]
I like this idea, though in my case, `s/Lincoln Mullen/Noam Ross/`.

**Comment by sckott** [comment]
thanks @noamross - if you want to use your name i'll wait for that before PR merge

**Comment by lmullen** [comment]
Oh, I wasn't complaining about using my name in the example and suggesting a change. I just meant that @noamross reviewed my package, so I'm planning to add him in that way. Sorry for my ambiguity.

**Comment by sckott** [comment]
ah, k, right, makes sense :)

**Pull request merged**
